name: Merge Feature Branch Into Develop

on:
  push:
    branches:
      - feature**

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s tests

  merge-feature-branch-into-develop:
    name: Merge Feature Branch Into Develop
    needs: run-unit-tests
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          ref: develop
          persist-credentials: true

      - name: Set bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge feature branch into develop
        run: |
          git fetch origin ${{ github.ref_name }}
          git merge origin/${{ github.ref_name }} --no-ff --no-edit
          git push origin develop